### PR TITLE
Cv2 support

### PR DESCRIPTION
**Pull request by igm503**
# Background

I'm using this library for a project where it's convenient to keep images that move through the pipeline in the cv2 numpy format. However, this means that I have to convert the cv2 arrays to PIL images, and then back to cv2 arrays, to use the Remover.process function. 

In this case, speed is important, and in some cases, using the preprocessing transforms from the [albumentations](https://github.com/albumentations-team/albumentations) library library on a cv2 image is faster than doing the corresponding transformers on PIL images. 

# Feature

The Remover class's process() function can take either PIL images or cv2 images. 

# Implementation

Remover now has a self.cv2_transform attribute, which is a composition of transforms from the [albumentations](https://github.com/albumentations-team/albumentations) library, plus a custom albumentations transform in written to match the dynamic_resize() function in transparent_background/utils.py. 

Remover.process() now checks whether the input is an np.ndarray or a PIL.Image.Image. If the input is an np.ndarray, it applies the cv2_transforms transforms and doesn't convert to a PIL.Image.Image before returning. If the input is a PIL.Image.Image, it functions as before.

# Speed Comparisons

Results are displayed for 3 machines I've tested on. "Remover" is s/frame for the bare remover.process call, and "Conversion" is the s/frame for cv2 -> PIL conversion and PIL -> cv2 conversion. 

The test results displayed below use the 'map' output type. 

See the test script below for more detail.

## Intel i7-13700K + Nvidia RTX 4070 (tests done on 1080p webcam)

Settings -> Mode=fast, Device=cuda, Torchscript=disabled
PIL -- FPS: 28.36, Remover: 0.0327, Conversion: 0.0025
CV2 --FPS: 38.35, Remover: 0.0261, Conversion: 0.0000

Settings -> Mode=base, Device=cuda, Torchscript=disabled
PIL -- FPS: 3.50, Remover: 0.2825, Conversion: 0.0030
CV2 -- FPS: 4.03, Remover: 0.2479, Conversion: 0.0000

## Intel i9-10940X + Nvidia RTX 4090 (tests done on a 900x700 img)

Settings -> Mode=fast, Device=cuda, Torchscript=disabled
PIL   -- FPS: 19.90, Remover: 0.0488, Conversion: 0.0015
CV2 -- FPS: 23.92, Remover: 0.0418, Conversion: 0.0000

Settings -> Mode=base, Device=cuda, Torchscript=disabled
PIL   -- FPS: 11.87, Remover: 0.0828, Conversion: 0.0015
CV2 -- FPS: 16.45, Remover: 0.0608, Conversion: 0.0000

## M2 Max w/ 38 GPU cores (tests done on ~1080p webcam)

Settings -> Mode=fast, Device=mps, Torchscript=disabled
PIL   -- FPS: 5.16, Remover: 0.1880, Conversion: 0.0058
CV2 -- FPS: 5.76, Remover: 0.1737, Conversion: 0.0000

Settings -> Mode=base, Device=cuda, Torchscript=disabled
PIL   -- FPS: 0.91, Remover: 1.0872, Conversion: 0.0070
CV2 -- FPS: 0.96, Remover: 1.0465, Conversion: 0.0000

## Test Script

```
import time

import cv2
from transparent_background import Remover
import numpy as np
from PIL import Image

cap = cv2.VideoCapture(0)

remover = Remover(mode='base', jit=False, device='mps')

num_loops = 10

# Warmup 

for i in range(5):
    ret, frame = cap.read()
    if ret:
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frame = Image.fromarray(frame)
        out = remover.process(frame, type='map')
        out = cv2.cvtColor(np.array(out), cv2.COLOR_RGB2BGR)

# Test with PIL

t_total = 0
t_remover = 0
num = 0

for i in range(num_loops):

    ret, frame = cap.read()

    if ret:
        t0 = time.perf_counter()
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frame = Image.fromarray(frame)
        t1 = time.perf_counter()
        out = remover.process(frame, type='map')
        t2 = time.perf_counter()
        out = cv2.cvtColor(np.array(out), cv2.COLOR_RGB2BGR)
        t4 = time.perf_counter()
        t_total += t4 - t0
        t_remover += t2 - t1
        num += 1

print('PIL')
print('==========')
print(f'FPS: {num / t_total:.2f}, Remover: {t_remover / num:.4f}, Conversion: {(t_total - t_remover) / num:.4f}')
print()

# Test with OpenCV

t_total = 0
t_remover = 0
num = 0

for i in range(num_loops):

    ret, frame = cap.read()

    if ret:
        t0 = time.perf_counter()
        # frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        # frame = Image.fromarray(frame)
        t1 = time.perf_counter()
        out = remover.process(frame, type='map')
        t2 = time.perf_counter()
        # out = cv2.cvtColor(np.array(out), cv2.COLOR_RGB2BGR)
        t4 = time.perf_counter()
        t_total += t4 - t0
        t_remover += t2 - t1
        num += 1

print('CV2')
print('==========')
print(f'FPS: {num / t_total:.2f}, Remover: {t_remover / num:.4f}, Conversion: {(t_total - t_remover) / num:.4f}')
print()
```

### CODE REVIEW

**Comment by eafpres** [comment]
I'm unsure if relevant but I've found larger than expected performance differences between CPU and GPU. Typical differences are 4x to 5x which are higher than other CV methods I've tested. Is this possibly related to conversion inefficiency?

**Comment by igm503** [comment]
@eafpres It might depend, but I suspect in general no--when I've profiled Remover.process() on cpu on the machines listed above, I'm seeing at most ~10% of the time being spent in the PIL -> Tensor preprocessing step. 

I've noticed something similar to what you're pointing out, though. I've been guessing that it's related to the size of the model, since a lot of the CV models I use tend to be smaller to be suitable for realtime use, and in those cases, the advantages of the gpu aren't as big as they would be for a bigger model, but the penalty of cpu->gpu memory transfer is just as big. Not sure if that's what your comparing to, though.

**Comment by plemeri** [comment]
Thank you for your effort! Let me check the difference between your branch and main branch real quick.

**Comment by plemeri** [comment]
cv2|PIL
:-:|:-:
test | test2

The difference is small but PIL input shows slightly better result. I'll merge this PR since the user can choose between PIL and cv2 for Python API, and cli-tool isn't changed. Hope this result difference could be solved in the future PRs. Thanks @igm503!

**Comment by igm503** [comment]
@plemeri Interesting! I'll try to check it out in the coming days and see if there are any easy fixes.

**Pull request merged**
